### ISSUE TITLE
Building pipeline requires local install of all python modules

### ISSUE THREAD

**Issue by EiffL** [joezuntz/descpipe#1]
I am trying to use `descpipe build` to generate the script for a custom pipeline. When `descpipe.pipeline` loads the configuration, it tries to load each run.py modules in the pipeline, and that fails because the necessary python dependencies are not necessarily installed on my local machine. 
Here is an example:

```[francois@Deneb WLMassMap]$ descpipe build pipeline/pipeline.yaml 
Traceback (most recent call last):
  File "/home/francois/.local/bin/descpipe", line 4, in <module>
    descpipe.ui.main()
  File "/home/francois/.local/lib/python3.6/site-packages/descpipe/ui.py", line 82, in main
    return task(args)        
  File "/home/francois/.local/lib/python3.6/site-packages/descpipe/ui.py", line 41, in build
    pipeline=Pipeline(args.pipe_file)
  File "/home/francois/.local/lib/python3.6/site-packages/descpipe/pipeline.py", line 27, in __init__
    self.stages[name] = self.load_stage(name)
  File "/home/francois/.local/lib/python3.6/site-packages/descpipe/pipeline.py", line 62, in load_stage
    module = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "./pipeline/images/extract_footprint/run.py", line 10, in <module>
    import desc.wlmassmap.mocks.extract_footprint
  File "/home/francois/repo/WLMassMap/python/desc/wlmassmap/mocks/extract_footprint.py", line 3, in <module>
    from GCRCatalogs import load_catalog
ModuleNotFoundError: No module named 'GCRCatalogs'
```
This GCRCatalogs module is installed inside the docker image for that pipeline step so that `run.py` can work inside the container, but I don't necessarily want to install it on my local environment. 

I wasn't expecting this behavior, is it really necessary to import the `run.py` modules to build the pipeline ?

**Comment by EiffL** [comment]
Ok, my bad, realized that putting the import inside the `run()` command solves the problem. Works fine.
